# Generated by Django 2.0.2 on 2018-02-22 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Creator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('Country', models.CharField(max_length=255)),
                ('Website', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255, unique=True)),
                ('ReleaseDate', models.CharField(max_length=255, unique=True)),
                ('LibVersion', models.CharField(max_length=255)),
                ('PythonVersion', models.IntegerField(choices=[('2', 'python 2'), ('3', 'python 3')])),
                ('Description', models.TextField()),
                ('Documentation', models.CharField(max_length=255)),
                ('CreatorID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basetest.Creator')),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255, unique=True)),
                ('Description', models.TextField()),
                ('LibraryID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basetest.Library')),
            ],
        ),
    ]
