# Generated by Django 2.0.2 on 2018-02-24 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basetest', '0002_auto_20180222_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='library',
            name='PythonVersion',
            field=models.IntegerField(choices=[(2, 'python 2'), (3, 'python 3')]),
        ),
    ]
