# Generated by Django 2.0.2 on 2018-02-24 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basetest', '0003_auto_20180224_1047'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments_text', models.CharField(max_length=255)),
                ('comments_article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basetest.Library')),
            ],
        ),
    ]
