# Generated by Django 2.0.2 on 2018-02-28 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basetest', '0005_auto_20180228_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='UserID',
            field=models.CharField(default='Гость', max_length=255),
        ),
    ]
