# Generated by Django 2.0.2 on 2018-02-28 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basetest', '0006_auto_20180228_2047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='LibraryID',
        ),
    ]
