# Generated by Django 2.0.2 on 2018-02-28 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basetest', '0007_remove_comments_libraryid'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='LibraryID',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='basetest.Library'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='UserID',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='basetest.Users'),
        ),
    ]
