# Generated by Django 2.0.2 on 2018-02-28 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basetest', '0008_auto_20180228_2100'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('CommentsText', models.CharField(default='Пустой комментарий', max_length=255)),
            ],
        ),
    ]
