# Generated by Django 2.0.2 on 2018-03-01 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basetest', '0009_comments2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comments2',
        ),
    ]
