# Generated by Django 2.0.2 on 2018-03-03 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basetest', '0012_auto_20180301_1622'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Class', models.CharField(max_length=30)),
                ('TaskText', models.CharField(max_length=100)),
            ],
        ),
    ]
