# Generated by Django 2.0.2 on 2018-03-18 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basetest', '0014_module_tasks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='TaskText',
            field=models.CharField(max_length=250),
        ),
    ]
