# Generated by Django 2.0.2 on 2018-03-25 08:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basetest', '0016_auto_20180325_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='UserID',
            field=models.ForeignKey(default=25, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL),
        ),
    ]
