# Generated by Django 2.0.2 on 2018-03-25 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basetest', '0017_auto_20180325_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='library',
            name='CreatorID',
            field=models.ForeignKey(default=87, on_delete=django.db.models.deletion.SET_DEFAULT, to='basetest.Creator'),
        ),
    ]
